#[[redirects]]
#    from = "/"
#    to = "/handler"
#    status = 404

[[edge_functions]]
    path = "/"
    function = "handler"

[build]
    publish = "dist"
    command = "pnpm build"
    edge_functions = "netlify/edge-functions"

[dev]
    port = 8888 # The port that the netlify dev will be accessible on
    publish = "dist"
    framework = "#static"
    command = "pnpm build:deno --watch" # Command to start your dev server
    # targetPort = 3000 # The port for your application server, framework or site generator
    autoLaunch = false
